[GLOBAL]
pants_version = "2.28.0"
backend_packages = [
    "pants.backend.python",
    "pants.backend.python.typecheck.mypy",
    "pants.backend.experimental.python.lint.ruff.check",
    "pants.backend.experimental.python.lint.ruff.format",
]
pythonpath = []

[source]
root_patterns = ["src", "frontend", "tests"]

[python]
interpreter_constraints = ["CPython==3.13.*"]
enable_resolves = true

[ruff]
config = "ruff.toml"

[mypy]
config = "mypy.ini"

[pytest]
# (we'll add tests later)
